### ISSUE TITLE
Improve Error Message on Stackset Resource

### ISSUE THREAD

**Issue by ConnorKirk** [aws-cloudformation/aws-cloudformation-resource-providers-cloudformation#17]
Hi!

When trying out the `AWS::CloudFormation::Stackset` resource, my deployment fails.

The error is my fault. I believe the error message could be improved. My understanding of the error message is that the `Stackset` resource does not match the schema definition. In this case, two required properties were missing.
I would appreciate a more informative explanation of where it is wrong, as other resources provide. 

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/17845406/94668771-57a53a80-0308-11eb-956c-aff0a0e0ab1e.png">

If possible, could you improve the error message returned by the resource in this scenario?

**Comment by PatMyron** [comment]
Agreed, but I actually think this can't be solved at the resource provider level
I believe this is a CloudFormation platform wide issue with [resource schema](https://github.com/aws-cloudformation/aws-cloudformation-resource-schema/) validation messages

**Comment by ConnorKirk** [comment]
Interesting, thanks Pat! I guess this isn't a change I can make a PR for then 😢 
I'll close this issue for now.
