### ISSUE TITLE
Use AWS::CloudFormation::StackSet in GovCloud?

### ISSUE THREAD

**Issue by atheiman** [aws-cloudformation/aws-cloudformation-resource-providers-cloudformation#18]
The CloudFormation resource AWS::CloudFormation::StackSet was recently released in most commercial regions, but not yet available in GovCloud: https://aws.amazon.com/about-aws/whats-new/2020/09/aws-cloudformation-now-supports-stacksets-resource-type-in-the-cloudformation-registry/.

Since the code is publicly available here - https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-cloudformation/tree/master/aws-cloudformation-stackset - is there a way I can use this in GovCloud now?

**Comment by xiwhuang** [comment]
Hi Austin, since StackSet resource is not publicly released in GovCloud, I would suggest to register it as a private resource in your accounts as a workaround. 

See this link for the reference. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/registry.html

**Comment by atheiman** [comment]
Yes this is what I ended up doing. I took notes on it here if anyone finds this looking for help: https://github.com/atheiman/acme-cloudformation-stackset

**Comment by atheiman** [comment]
Looks like the `AWS::CloudFormation::StackSet` resource has been released to govcloud as of a few weeks ago (at least thats when I first noticed it there). Closing this.
