### ISSUE TITLE
A Typo in AWS Document for stacksets

### ISSUE THREAD

**Issue by philipakash** [aws-cloudformation/aws-cloudformation-resource-providers-cloudformation#20]
There is a typo in the PermissionModel. Almost spent 2 hours with my team to figure out the error and finally saw this as a typo in the document LoL.

https://docs.aws.amazon.com/en_us/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-stackset.html#cfn-cloudformation-stackset-permissionmodel

**Comment by rachfop** [comment]
Hello @philipakash thank you for providing your feedback. I have fixed the documents here on GitHub and the changes will be fixed on the public site shortly.

**Comment by philipakash** [comment]
Thanks @rachfop
