### ISSUE TITLE
AWS::CloudFormation::StackSet doesn't allow common tag keys

### ISSUE THREAD

**Issue by jfoy** [aws-cloudformation/aws-cloudformation-resource-providers-cloudformation#59]
Our organization uses tag keys of the form `org:billto:costcenter` for common cost tagging across all AWS resources, which we adopted under guidance from the AWS Cost and Usage Report team. The `AWS::CloudFormation::StackSet` resource schema forbids tags of this form since they contain colons. We cannot easily fold together alternative tags declared as `org/billto/costcenter`, for example, using the AWS-provided cost aggregation functions.

I understand reserving tag namespaces like `aws:`, but is there an obstacle to supporting such a common AWS-endorsed tagging scheme?

**Comment by benbridts** [comment]
See also #15 

The [API docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_Tag.html) only mention a minumum and a maximum.

@jfoy Did you test this with the API/CLI to confirm that it's supported there?

**Comment by jfoy** [comment]
Yes, this works through the CLI.

**Comment by xiwhuang** [comment]
This has been addressed in #60
